name: GitHub 3D Contribution Skyline & Snake

on:
  schedule:
    - cron: "0 18 * * *" # Every day at 18:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-3d:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Skyline
    steps:
      - uses: actions/checkout@v4
      - uses: y-hiraoka/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push 3D Skyline
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "Update 3D Contribution Skyline" || exit 0
          git push
